---
- name: Deploy alert rule files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ svc_prometheus_config_dir }}/rules/"
    owner: root
    group: prometheus
    mode: "0640"
    validate: "{{ svc_prometheus_install_dir }}/promtool check rules %s"
  loop:
    - node.rules.yml
    - prometheus.rules.yml
    - watchdog.rules.yml
    - blackbox.rules.yml
  notify: Restart prometheus

- name: Deploy blackbox probe targets
  ansible.builtin.template:
    src: "blackbox_{{ item }}_targets.json.j2"
    dest: "{{ svc_prometheus_config_dir }}/targets/blackbox_{{ item }}.json"
    owner: root
    group: prometheus
    mode: "0640"
  loop:
    - https
    - http
    - tcp
    - dns

- name: Deploy prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ svc_prometheus_config_dir }}/prometheus.yml"
    owner: root
    group: prometheus
    mode: "0640"
    validate: "{{ svc_prometheus_install_dir }}/promtool check config %s"
  notify: Restart prometheus

- name: Deploy node fleet targets
  ansible.builtin.template:
    src: node_targets.json.j2
    dest: "{{ svc_prometheus_config_dir }}/targets/node_fleet.json"
    owner: root
    group: prometheus
    mode: "0640"
