---
- name: Lab baseline
  hosts: rhel
  become: true
  roles:
    - role: rhel_registration
      tags: rhel_registration
    - role: rhel_ssh_hardening
      tags: rhel_ssh_hardening
    - role: rhel_selinux
      tags: rhel_selinux
    - role: rhel_firewalld
      tags: rhel_firewalld
    - role: rhel_chrony
      tags: rhel_chrony
    - role: rhel_updates
      tags: rhel_updates
    - role: rhel_packages
      tags: rhel_packages
    - role: rhel_dns_resolver
      tags: rhel_dns_resolver
    - role: rhel_monitoring_agent
      tags: rhel_monitoring_agent

- name: Ubuntu baseline
  hosts: ubuntu
  become: true
  roles:
    - role: ubuntu_ssh_hardening
      tags: ubuntu_ssh_hardening
    - role: ubuntu_apparmor
      tags: ubuntu_apparmor
    - role: ubuntu_ufw
      tags: ubuntu_ufw
    - role: ubuntu_chrony
      tags: ubuntu_chrony
    - role: ubuntu_updates
      tags: ubuntu_updates
    - role: ubuntu_packages
      tags: ubuntu_packages
