---
rhel_monitoring_agent_ne_version: "{{ lab_node_exporter_version }}"
rhel_monitoring_agent_ne_sha256: "{{ lab_node_exporter_sha256 }}"
rhel_monitoring_agent_ne_base: "{{ lab_node_exporter_base }}"
rhel_monitoring_agent_ne_archive: "{{ lab_node_exporter_archive }}"
