---
all:
  children:
    rhel:
      hosts:
        ns1.lab.eugeneivanov.dev:
        ns2.lab.eugeneivanov.dev:
        ca.lab.eugeneivanov.dev:
        admin.lab.eugeneivanov.dev:
        vpn.lab.eugeneivanov.dev:
        monitor.lab.eugeneivanov.dev:
        test240.lab.eugeneivanov.dev:
    ubuntu:
      hosts:
        news.lab.eugeneivanov.dev:
        webaudit.lab.eugeneivanov.dev:
        umami.lab.eugeneivanov.dev:
        mc.lab.eugeneivanov.dev:
        plausible.lab.eugeneivanov.dev:
        matomo.lab.eugeneivanov.dev:
    monitoring:
      hosts:
        monitor.lab.eugeneivanov.dev:
        test240.lab.eugeneivanov.dev:
