---
- name: Ensure baseline packages are installed
  ansible.builtin.apt:
    name:
      - vim
      - bash-completion
      - tar
      - unzip
      - bind9-dnsutils
      - openssl
      - qemu-guest-agent
    state: present
