---
- name: Create blackbox_exporter config directory
  ansible.builtin.file:
    path: "{{ svc_blackbox_exporter_config_dir }}"
    state: directory
    owner: root
    group: blackbox_exporter
    mode: "0750"

- name: Deploy blackbox.yml
  ansible.builtin.template:
    src: blackbox.yml.j2
    dest: "{{ svc_blackbox_exporter_config_dir }}/blackbox.yml"
    owner: root
    group: blackbox_exporter
    mode: "0640"
  notify: Restart blackbox_exporter
